# HTTP Server
server:
  port: 0   # HTTP (Tomcat) port

eureka:
 instance:
  instanceId: ${spring.application.name}:${server.port} 
 client:
  service-url:
    defaultZone: http://localhost:8011/eureka,http://localhost:8012/eureka,http://localhost:8013/eureka 
